### ISSUE TITLE
[Linux] Builds are now failing

### ISSUE THREAD

**Issue by Shoegzer** [trzy/Supermodel#287]
Builds fail with:

```
Src/CPU/68K/Musashi/m68kcpu.c: In function ‘m68k_execute’:
Src/CPU/68K/Musashi/m68kcpu.c:747:25: error: ‘m68ki_instruction_jump_table’ undeclared (first use in this function)
  747 |                         m68ki_instruction_jump_table[REG_IR]();
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
Compiling              : obj/m68kopdm.c -> obj/m68kopdm.o
Src/CPU/68K/Musashi/m68kcpu.c: In function ‘m68k_init’:
Src/CPU/68K/Musashi/m68kcpu.c:822:17: error: implicit declaration of function ‘m68ki_build_opcode_table’ [-Wimplicit-function-declaration]
  822 |                 m68ki_build_opcode_table();
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefiles/Rules.inc:402: obj/m68kcpu.o] Error 1
make: *** Waiting for unfinished jobs....
```
Test details:
* OS: Linux Mint 22.2 / kernel 6.14
* CPU: Intel i9-14900HX
* Bad commit: 99dc9171f72ee8e68573dcecc861655ce3ae79de
* Last known good commit: 6b0f050186922d7e6032d2898c7061764c384b67
* Build log: [build.log](https://github.com/user-attachments/files/23376878/build.log)
