### ISSUE TITLE
Supermodel no longer builds on linux

### ISSUE THREAD

**Issue by Shoegzer** [trzy/Supermodel#108]
Supermodel is no longer building on linux systems as of the last few days (see commit details below).  

Build attempt produces the following in the log:

```
Src/Graphics/New3D/New3D.cpp: In member function ‘void New3D::CNew3D::DescendCullingNode(UINT32)’:
Src/Graphics/New3D/New3D.cpp:722:28: error: ‘FLT_MAX’ was not declared in this scope
  722 |                 LODscale = FLT_MAX;
      |                            ^~~~~~~
```
Test system:
* OS: Linux Mint 21.2 / kernel 6.2
* Compiler: gcc-12.3.0
* Bad commit: cdf5e4b2b26323fe68d828c0dbccf05b2661768f
* Last good commit: 3022e418c7c74f9f56f06953f283f9ed2da5663a
* Build log: [build.log](https://github.com/trzy/Supermodel/files/13395055/build.log)

**Comment by dukeeeey** [comment]
try now
